package gui;

import classes.Cliente;
import classes.Diretor;
import classes.Engenheiro;
import classes.Gerente;
import classes.Secretario;
import java.util.ArrayList;

public class FrImprimir extends javax.swing.JFrame {
    public ArrayList<Cliente> lstCliente;
    public ArrayList<Engenheiro> lstEngenheiro;
    public ArrayList<Diretor> lstDiretor;
    public ArrayList<Secretario> lstSecretario;
    public ArrayList<Gerente> lstGerente;

    public FrImprimir() {
        initComponents();
        edtNome.setEnabled(false);
        edtIdade.setEnabled(false);
        edtSexo.setEnabled(false);
        edtSalario.setEnabled(false);
        edtCpf.setEnabled(false);
        edtNumPessoasGerenciadas.setEnabled(false);
        edtSenha.setEnabled(false);
        edtHorasTrabalhadas.setEnabled(false);
        
        this.lstCliente = new ArrayList();
        this.lstEngenheiro = new ArrayList();
        this.lstDiretor = new ArrayList();
        this.lstSecretario = new ArrayList();
        this.lstGerente = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnCliente = new javax.swing.JRadioButton();
        btnEngenheiro = new javax.swing.JRadioButton();
        btnDiretor = new javax.swing.JRadioButton();
        btnSecretario = new javax.swing.JRadioButton();
        btnGerente = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtResultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtIdade = new javax.swing.JTextField();
        edtSexo = new javax.swing.JTextField();
        edtSalario = new javax.swing.JTextField();
        edtCpf = new javax.swing.JTextField();
        edtNumPessoasGerenciadas = new javax.swing.JTextField();
        edtSenha = new javax.swing.JTextField();
        edtHorasTrabalhadas = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(btnCliente);
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnEngenheiro);
        btnEngenheiro.setText("Engenheiro");
        btnEngenheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngenheiroActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDiretor);
        btnDiretor.setText("Diretor");
        btnDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiretorActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnSecretario);
        btnSecretario.setText("Secretario");
        btnSecretario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecretarioActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnGerente);
        btnGerente.setText("Gerente");
        btnGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenteActionPerformed(evt);
            }
        });

        edtResultado.setColumns(20);
        edtResultado.setRows(5);
        jScrollPane1.setViewportView(edtResultado);

        jLabel1.setText("Nome:");

        jLabel2.setText("Sexo:");

        jLabel3.setText("Idade:");

        jLabel4.setText("Cpf:");

        jLabel5.setText("Horas Trabalhadas:");

        jLabel6.setText("Salário:");

        jLabel7.setText("Senha:");

        jLabel8.setText("Nº de pessoas gerenciadas:");

        edtNumPessoasGerenciadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNumPessoasGerenciadasActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEngenheiro)
                        .addGap(18, 18, 18)
                        .addComponent(btnDiretor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSecretario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGerente)
                        .addGap(58, 58, 58)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(30, 30, 30))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(24, 24, 24)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edtSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(edtCpf)
                                    .addComponent(edtSalario)
                                    .addComponent(edtSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(edtIdade)
                                    .addComponent(edtNome)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtNumPessoasGerenciadas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliente)
                    .addComponent(btnEngenheiro)
                    .addComponent(btnDiretor)
                    .addComponent(btnSecretario)
                    .addComponent(btnGerente)
                    .addComponent(btnSalvar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(edtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(edtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(edtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edtHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(edtNumPessoasGerenciadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        edtNome.setEnabled(true);
        edtIdade.setEnabled(true);
        edtSexo.setEnabled(true);
        edtSalario.setEnabled(false);
        edtCpf.setEnabled(true);
        edtNumPessoasGerenciadas.setEnabled(false);
        edtSenha.setEnabled(false);
        edtHorasTrabalhadas.setEnabled(false);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnEngenheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngenheiroActionPerformed
        edtNome.setEnabled(true);
        edtIdade.setEnabled(true);
        edtSexo.setEnabled(true);
        edtSalario.setEnabled(true);
        edtCpf.setEnabled(false);
        edtNumPessoasGerenciadas.setEnabled(false);
        edtSenha.setEnabled(false);
        edtHorasTrabalhadas.setEnabled(true);
    }//GEN-LAST:event_btnEngenheiroActionPerformed

    private void edtNumPessoasGerenciadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNumPessoasGerenciadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNumPessoasGerenciadasActionPerformed

    private void btnDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiretorActionPerformed
        edtNome.setEnabled(true);
        edtIdade.setEnabled(true);
        edtSexo.setEnabled(true);
        edtSalario.setEnabled(true);
        edtCpf.setEnabled(false);
        edtNumPessoasGerenciadas.setEnabled(false);
        edtSenha.setEnabled(true);
        edtHorasTrabalhadas.setEnabled(true);
    }//GEN-LAST:event_btnDiretorActionPerformed

    private void btnSecretarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecretarioActionPerformed
        edtNome.setEnabled(true);
        edtIdade.setEnabled(true);
        edtSexo.setEnabled(true);
        edtSalario.setEnabled(true);
        edtCpf.setEnabled(false);
        edtNumPessoasGerenciadas.setEnabled(false);
        edtSenha.setEnabled(false);
        edtHorasTrabalhadas.setEnabled(true);
    }//GEN-LAST:event_btnSecretarioActionPerformed

    private void btnGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenteActionPerformed
        edtNome.setEnabled(true);
        edtIdade.setEnabled(true);
        edtSexo.setEnabled(true);
        edtSalario.setEnabled(true);
        edtCpf.setEnabled(false);
        edtNumPessoasGerenciadas.setEnabled(true);
        edtSenha.setEnabled(true);
        edtHorasTrabalhadas.setEnabled(true);
    }//GEN-LAST:event_btnGerenteActionPerformed
    
    private void limparTexto(){
        edtNome.setText("");
        edtIdade.setText("");
        edtSexo.setText("");
        edtSalario.setText("");
        edtCpf.setText("");
        edtNumPessoasGerenciadas.setText("");
        edtSenha.setText("");
        edtHorasTrabalhadas.setText("");        
    }
    
    private void salvarCliente(){
        String nome = edtNome.getText();
        int idade = Integer.parseInt(edtIdade.getText());
        char sexo = edtSexo.getText().charAt(0);
        String cpf = edtCpf.getText();
            
        Cliente c = new Cliente();
        c.preencher(nome, sexo, idade, cpf);
        
        lstCliente.add(c);
        
        String imprimirFr = "";
        for(int i = 0; i < lstCliente.size(); ++i){
            imprimirFr = imprimirFr + lstCliente.get(i).imprime() + "\n\n";
        }

        edtResultado.setText(imprimirFr);
    }
    
    private void salvarEngenheiro(){
        String nome = edtNome.getText();
        int idade = Integer.parseInt(edtIdade.getText());
        char sexo = edtSexo.getText().charAt(0);
        float horasTrabalho = Float.parseFloat(edtHorasTrabalhadas.getText());
        float salario = Float.parseFloat(edtSalario.getText());
            
        Engenheiro e = new Engenheiro();
        e.preencher(nome, sexo, idade, horasTrabalho, salario);
        
        lstEngenheiro.add(e);
        
        String imprimirFr = "";
        for(int i = 0; i < lstEngenheiro.size(); ++i){
            imprimirFr = imprimirFr + lstEngenheiro.get(i).imprime() + "\n\n";
        }
        
        edtResultado.setText(imprimirFr);
    }
    
    private void salvarDiretor(){
        String nome = edtNome.getText();
        int idade = Integer.parseInt(edtIdade.getText());
        char sexo = edtSexo.getText().charAt(0);
        float horasTrabalho = Float.parseFloat(edtHorasTrabalhadas.getText());
        float salario = Float.parseFloat((edtSalario.getText()));
        String senha = edtSenha.getText();
        
        Diretor d = new Diretor();
        d.preencher(nome, sexo, idade, horasTrabalho, salario, senha);
        
        lstDiretor.add(d);
        
        String imprimirFr = "";
        for(int i = 0; i < lstDiretor.size(); ++i){
            imprimirFr = imprimirFr + lstDiretor.get(i).imprime() + "\n\n";
        }
        
        edtResultado.setText(imprimirFr);
    }
    
    private void salvarSecretario(){
        String nome = edtNome.getText();
        int idade = Integer.parseInt(edtIdade.getText());
        char sexo = edtSexo.getText().charAt(0);
        float horasTrabalho = Float.parseFloat(edtHorasTrabalhadas.getText());
        float salario = Float.parseFloat((edtSalario.getText()));
        
        Secretario s = new Secretario();
        s.preencher(nome, sexo, idade, horasTrabalho, salario);
        
        lstSecretario.add(s);
        
        String imprimirFr = "";
        for(int i = 0; i < lstSecretario.size(); ++i){
            imprimirFr = imprimirFr + lstSecretario.get(i).imprime() + "\n\n";
        }
        
        edtResultado.setText(imprimirFr);
    }
    
    private void salvarGerente(){
        String nome = edtNome.getText();
        int idade = Integer.parseInt(edtIdade.getText());
        char sexo = edtSexo.getText().charAt(0);
        float horasTrabalho = Float.parseFloat(edtHorasTrabalhadas.getText());
        float salario = Float.parseFloat((edtSalario.getText()));
        String senha = edtSenha.getText();
        int pessoasGerenciadas = Integer.parseInt(edtNumPessoasGerenciadas.getText());
        
        Gerente g = new Gerente();
        g.preencher(nome, sexo, idade, horasTrabalho, salario, senha, pessoasGerenciadas);
        
        lstGerente.add(g);
        
        String imprimirFr = "";
        for(int i = 0; i < lstGerente.size(); ++i){
            imprimirFr = imprimirFr + lstGerente.get(i).imprime() + "\n\n";
        }
        
        edtResultado.setText(imprimirFr);
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(btnCliente.isSelected()){
            salvarCliente();
            limparTexto();
        }
        if(btnEngenheiro.isSelected()){
            salvarEngenheiro();
            limparTexto();
        }
        if(btnDiretor.isSelected()){
            salvarDiretor();
            limparTexto();
        }
        if(btnSecretario.isSelected()){
            salvarSecretario();
            limparTexto();
        }
        if(btnGerente.isSelected()){
            salvarGerente();
            limparTexto();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrImprimir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrImprimir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCliente;
    private javax.swing.JRadioButton btnDiretor;
    private javax.swing.JRadioButton btnEngenheiro;
    private javax.swing.JRadioButton btnGerente;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JRadioButton btnSecretario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtHorasTrabalhadas;
    private javax.swing.JTextField edtIdade;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtNumPessoasGerenciadas;
    private javax.swing.JTextArea edtResultado;
    private javax.swing.JTextField edtSalario;
    private javax.swing.JTextField edtSenha;
    private javax.swing.JTextField edtSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
